
# restore_model: ''
restore_model: content/drive/MyDrive/AR-SA-TTS/v1/states.pth

# restore_model: ./checkpoints/exp_tc2_adv/states.pth

log_dir: logs/exp_tc2_adv
checkpoint_dir: /content/drive/MyDrive/AR-SA-TTS/v1

train_wavs_path: /content/modeltts-ar/newdata
train_labels: ./data/SA/train_arab.txt

test_wavs_path: /content/modeltts-ar/newdata
test_labels: ./data/SA/train_phon.txt

label_pattern: '"(?P<filename>.*)" "(?P<arabic>.*)"'
#label_pattern: (?P<arabic>.*)\|(?P<filestem>.*)

# loss weights
gan_loss_weight: 4.
feat_loss_weight: 1.

# optimizers
g_lr: 1.0e-4    # lr for AdamW optimizer (generator)
g_beta1: 0.9     # beta1 for AdamW optimizer (generator)
g_beta2: 0.99   # beta2 for AdamW optimizer (generator)

d_lr: 1.0e-4    # lr for AdamW optimizer (discriminator)
d_beta1: 0.8     # beta1 for AdamW optimizer (discriminator)
d_beta2: 0.99   # beta2 for AdamW optimizer (discriminator)

n_save_states_iter: 10
n_save_backup_iter: 1000

